# Q187

`catchError()`メソッドを使用して、`Future`の実行中に発生したエラーを処理するプログラムを書いてください。
